apiVersion: apps/v1
kind: Deployment
metadata:
  name: rps
  annotations: 
    dns.details.html.spinnaker.io="<a href='https://${parameters.dns}.se.armory.io'>${parameters.dns}.se.armory.io</a>"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rps
  template:
    metadata:
      labels:
        app: rps
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: rps-config
          image: 'index.docker.io/away168/rps'
          name: rps
          ports:
            - containerPort: 80
