name: Publish Docker image
on:
  push:
    branches:
      - master
      - feature/pipeline
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: away168
          password: ${{ secrets.DOCKER_AWAY168 }}
      - name: Push to Docker Hub
        run: ./scripts/docker-build.sh
